version: "3"

services:
  nginx:
    image: nginx
    container_name: "project2_nginx"
    volumes:
    - ./:/app:ro
    - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: "always"
    labels:
      - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.project2.com"
    networks:
    - default
    - project2

  php:
    build: 
      dockerfile: Dockerfile
      context: ./.docker/php
    container_name: "project2_php"
    volumes:
    - ./:/app
    restart: "always"
    networks:
    - project2

  db:
    image: mariadb:10.2
    container_name: "project2_db"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./data/mariadb:/var/lib/mysql
    networks:
    - project2

  redis:
    image: redis
    container_name: "project2_redis"
    restart: "always"
    networks:
      - project2

  readis:
    image: hollodotme/readis
    container_name: "project2_readis"
    restart: "always"
    volumes:
      - ./.docker/readis:/code/config:ro
    networks:
      - project2

  composer:
      image: composer
      container_name: "project2_composer"
      restart: "no"
      volumes:
        - ./:/app
      networks:
        - project2
      command: "update -o -v"

networks:
  default:
    external:
      name: gateway

  project2:
    internal: true
